### ISSUE TITLE
登陆页面刷新后无法获取已存的token

### ISSUE THREAD

**Issue by chuhemiao** [chende008/react-native-easy-app#1]
我首先在config定义了 RNStorage，
export const RNStorage = {
    mobile: undefined,
    token: undefined,
    json: undefined,//测试符串
};
引用后使用XStorage.initStorage 存储
XStorage.initStorage(RNStorage, () => {
              RNStorage.token = res.data.token; 
             console.log('token9999=' + RNStorage.token); 
});

res.data.token是后端API返回的token，当前的console可以拿到token数据，然后请求后跳转的页面也可以取到token，但是重新刷新页面后，判断当前token是否存在，一直拿不到token，一直获取的是undefined，正常逻辑是如果token存在进到首页，否则去登陆页，我是在设置路由的时候判断当前走主页还是登陆页，Navigation.setRoot(isLoggedIn() ? Routers : LOGIN); isLoggedIn是获取token的一个方法，但是此方法打印的  console.log(RNStorage.token,666) 一直是undefined ，麻烦问下是使用的方法不对吗😂

**Comment by chende008** [comment]
这样交流不太方便，建议加QQ群，656061613，在群里直接交流

**Comment by chuhemiao** [comment]
@chende008 搜不到，群号写错了吗。。。

**Comment by chende008** [comment]
> @chende008 搜不到，群号写错了吗。。。

![image](https://user-images.githubusercontent.com/4397067/83226968-ac4b7400-a1b5-11ea-8598-e3b135e209b1.png)

**Comment by chende008** [comment]
> @chende008 搜不到，群号写错了吗。。。

当前开源库，主页readme文件中有二维码，扫码加吧。
