### ISSUE TITLE
XImage不接受require，icon的属性不应该写成PropType.string

### ISSUE THREAD

**Issue by haikerenwu** [chende008/react-native-easy-app#2]

**Comment by chende008** [comment]
是的，属性定义为PropType.string的确不太合适，但并不影响其支持require的形式设置图片，如：<XImage style={{width: '90%', height: 200}} icon={require('../../../../images/conan.jpeg')}/> 这样设置图片是可以正常显示的，参考代码：https://github.com/chende008/react-native-easy-app-sample/blob/master/src/Main/Home/view/WidgetController.js
至于icon的类型描述，最新版本现已修改。

**Comment by chende008** [comment]
另外readme文档中有QQ讨论群二维码，可以扫码加入进一步讨论，

**Comment by chende008** [comment]
确认支持require('./image.jpg'),上面有示例可以参考
