### ISSUE TITLE
XHttp写的很棒，但是作为习惯了客户端开发的人来说，应该要提供接口缓存的功能，个人觉得这个功能非常有必要

### ISSUE THREAD

**Issue by haikerenwu** [chende008/react-native-easy-app#3]

**Comment by chende008** [comment]
请求缓存的实现，受本地存储条件的影响不太好处理，特别是若App部分逻辑存在大量、高频的前后台数据交互的话，可能缓存的效率与性能就更不好说了。

所以这样的功能还是开发者自己实现比较好。至于实现方式：可以在XHttpConfig.initParseDataFunc()对接口请求的结果进缓存及回调处理。

**Comment by haikerenwu** [comment]
我觉得可以提供api的接口缓存配置，包括存储的配置

**Comment by chende008** [comment]
你可以fork一个版本，加上相关的功能实现，如果后面综合性能达到要求的话，我可以合并到master分支。

**Comment by haikerenwu** [comment]
好的
