### ISSUE TITLE
initParseDataFunc方法不进入

### ISSUE THREAD

**Issue by yuxiaochao** [chende008/react-native-easy-app#4]
`export default class HttpConfig {
  static init() {
    XHttpConfig()
      .initBaseUrl(APP_SERVE_URL_BD)
      .initTimeout(15000)
      .initHttpLogOn(false)
      .initContentType(XHttpConst.CONTENT_TYPE_URLENCODED)
      .initLoadingFunc((isLoading) => {})
      .initHeaderSetFunc((headers, request) => {
        // console.log(headers,request)
      })
      .initParamSetFunc((params, request) => {
        // console.log(params,request)
      })
      .initParseDataFunc((result, request, callback) => {
        let {success, json, message, status, response} = result;
        console.log("===================")
      })
      .initEncodeURIComponent(false);
  }
}`

initParseDataFunc方法不进入，initHeaderSetFunc、initParamSetFunc方法是可以进入的，能看一下是什么原因吗？

**Comment by chende008** [comment]
肯定在请求时设置了rawData()，它的作用是：【设置返回的接口数据是否为原始未处理过的数据；若调用，则会忽略XHttpConfig中设置**[initParseDataFunc]**函数】。 建议参考Demo相关用法，确认相关功能的使用
