### ISSUE TITLE
Text的icon属性，类型也有问题，不能直接require

### ISSUE THREAD

**Issue by haikerenwu** [chende008/react-native-easy-app#5]

**Comment by chende008** [comment]
或许不同的编辑器对类型检查，表现的结果不一样，我用的webStorm在Text的icon中使用require并不会有任何类型检查错误提示，当然，我现在已经加上了PropType.any ：require('xxx')对应的类型；

另外‘不能直接require’是什么意思？是说不支持require么？如果是，那可能是你的用法不对吧，你可以参考示例项目：Sample：https://github.com/chende008/react-native-easy-app-sample 中的 WidgetController 中Text的icon的用法：

<XText style={styles.iconText} text='文本' icon={require('../../../../images/conan.jpeg')} iconSize={20} iconPosition='right'/>
这样用，图片是可以正常显示的，你也可以把示例项目运行起来看看效果。

另外有问题的话，建议加QQ群（开源库的readme文件中有加QQ群的二维码），在群里直接@我，我可以第一时间给需要的朋友们释疑。
